baseURL = 'https://rafaeljaime.github.io/'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
theme = 'PaperMod'

# Permitir HTML en markdown
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Configuración global
[params]
  mainSections = ["projects"]
  ShowShareButtons = true

# Configuración de idiomas
[languages]
  [languages.en]
    title = "Rafael Jaime"
    languageCode = 'en-US'
    languageName = "English"
    weight = 1
    
    [languages.en.params]
      author = "Rafael Jaime"
      description = "Rafael Jaime's personal portfolio"
      ShowReadingTime = false
      ShowShareButtons = true
      ShowPostNavLinks = true
      ShowBreadCrumbs = true
      ShowCodeCopyButtons = true
      ShowWordCount = false
      ShowRssButtonInSectionTermList = true
      UseHugoToc = true
      disableSpecial1stPost = false
      disableScrollToTop = false
      comments = false
      hidemeta = true
      hideSummary = false
      showtoc = false
      tocopen = false
      
      [languages.en.params.profileMode]
        enabled = true
        title = "Rafael Jaime"
        subtitle = "Full Stack Developer & Software Engineer"
        imageUrl = ""
        imageTitle = "Rafael Jaime"
        
        [[languages.en.params.profileMode.buttons]]
          name = "Projects"
          url = "/en/projects/"
        
        [[languages.en.params.profileMode.buttons]]
          name = "About"
          url = "/en/about/"
      
      [languages.en.params.assets]
        disableHLJS = false
        disableFingerprinting = false
        
        [[languages.en.params.assets.css]]
          src = "/css/custom.css"

    [[languages.en.params.socialIcons]]
      name = "github"
      url = "https://github.com/RafaelJaime"
    
    [[languages.en.params.socialIcons]]
      name = "linkedin"
      url = "https://github.com/RafaelJaime"
    
    [[languages.en.params.socialIcons]]
      name = "email"
      url = "https://github.com/RafaelJaime"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "home"
        name = "Home"
        url = "/en/"
        weight = 10
      
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/en/projects/"
        weight = 20
      
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/en/about/"
        weight = 30

  [languages.es]
    title = "Rafael Jaime"
    languageCode = 'es-ES'
    languageName = "Español"
    weight = 2
    
    [languages.es.params]
      author = "Rafael Jaime"
      description = "Portfolio personal de Rafael Jaime"
      ShowReadingTime = false
      ShowShareButtons = true
      ShowPostNavLinks = true
      ShowBreadCrumbs = true
      ShowCodeCopyButtons = true
      ShowWordCount = false
      ShowRssButtonInSectionTermList = true
      UseHugoToc = true
      disableSpecial1stPost = false
      disableScrollToTop = false
      comments = false
      hidemeta = true
      hideSummary = false
      showtoc = false
      tocopen = false
      
      [languages.es.params.profileMode]
        enabled = true
        title = "Rafael Jaime"
        subtitle = "Desarrollador Full Stack e Ingeniero de Software"
        imageUrl = ""
        imageTitle = "Rafael Jaime"
        
        [[languages.es.params.profileMode.buttons]]
          name = "Proyectos"
          url = "/es/projects/"
        
        [[languages.es.params.profileMode.buttons]]
          name = "Acerca de"
          url = "/es/about/"
      
      [languages.es.params.assets]
        disableHLJS = false
        disableFingerprinting = false
        
        [[languages.es.params.assets.css]]
          src = "/css/custom.css"

    [[languages.es.params.socialIcons]]
      name = "github"
      url = "https://github.com/RafaelJaime"

    [languages.es.menu]
      [[languages.es.menu.main]]
        identifier = "home"
        name = "Inicio"
        url = "/es/"
        weight = 10
      
      [[languages.es.menu.main]]
        identifier = "projects"
        name = "Proyectos"
        url = "/es/projects/"
        weight = 20
      
      [[languages.es.menu.main]]
        identifier = "about"
        name = "Acerca de"
        url = "/es/about/"
        weight = 30
